### Buscar todas as compra
GET http://localhost:3000/compra

### Buscar categoria por ID
GET http://localhost:3000/compra/1

### Criar nova categoria
POST http://localhost:3000/compra
Content-Type: application/json

### Atualizar categoria
PUT http://localhost:3000/compra/1
Content-Type: application/json

{
  "nome": "Tech Atualizado",
  "descricao": "Nova descrição"
}

### Deletar categoria
DELETE http://localhost:3000/compra/1